services:
  mysql:
    image: mysql:8.0
    container_name: eventhub_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventhub_core
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: eventhub_redis
    ports:
      - "6379:6379"

  core-api:
    build:
      context: ./core-api
      dockerfile: Dockerfile
    container_name: eventhub_core_api
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./core-api:/var/www/html
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: eventhub_core
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      PAYMENT_SERVICE_URL: http://payment-service:8001
      NOTIFICATION_SERVICE_URL: http://notification-service:3002
      NOTIFICATION_SERVICE_SECRET: secure_shared_secret
      PAYMENT_SERVICE_SECRET: secure_shared_secret

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: eventhub_payment_service
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./payment-service:/var/www/html
    depends_on:
      - redis
    environment:
      APP_ENV: local
      APP_KEY: base64:I4lIuNQ/ohBnMUjHt0SmF5tBpjBKag7XWDEjPzvD62Q=
      QUEUE_CONNECTION: database
      PAYMENT_SERVICE_SECRET: secure_shared_secret
      CORE_API_URL: http://core-api:80
      STRIPE_SUCCESS_RATE: 0.9
      PAYPAL_SUCCESS_RATE: 0.8

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: eventhub_notification_service
    restart: unless-stopped
    ports:
      - "3002:3002"
    volumes:
      - ./notification-service:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      PORT: 3002
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CORE_API_URL: http://core-api:80
      CORE_API_SECRET: secure_shared_secret
      WEBHOOK_TIMEOUT_MS: 5000
      WEBHOOK_MAX_RETRIES: 3
      WEBHOOK_RETRY_DELAY_MS: 1000
      LOG_LEVEL: info

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eventhub_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - core-api

volumes:
  mysql_data:
