services:
  mysql:
    image: mysql:8.0
    container_name: eventhub_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventhub_core
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: eventhub_redis
    ports:
      - "6379:6379"

  core-api:
    build:
      context: ./core-api
      dockerfile: Dockerfile
    container_name: eventhub_core_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./core-api:/var/www/html
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: eventhub_core
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis

volumes:
  mysql_data: